# Comprehensive CWMS code mapping
# Based on USACE documentation and known working codes

RESERVOIR_CODE_MAPPING = {
    "Aberdeen Lake": "ABER",
    "Abiquiu Reservoir": "ABIQ",
    "Alamo Lake": "ALAM",
    "Aliceville Lake": "ALIC",
    "Allegheny Reservoir": "ALLE",
    "Alum Creek Lake": "ALUM",
    "Applegate Lake": "APPL",
    "Aquilla Lake": "AQUI",
    "Arcadia Lake": "ARCA",
    "Arkabutla Lake": "ARKA",
    "Arkansas River Pool 13": "AR13",
    "Arkansas River Pool 2": "ARP2",
    "Arkansas River Pool 3": "ARP3",
    "Arkansas River Pool 4": "ARP4",
    "Arkansas River Pool 5": "ARP5",
    "Arkansas River Pool 6": "ARP6",
    "Arkansas River Pool 7": "ARP7",
    "Arkansas River Pool 8": "ARP8",
    "Arkansas River Pool 9": "ARP9",
    "Atwood Lake": "ATWO",
    "B. Everett Jordan Lake": "JORD",
    "Ball Mountain Lake": "BALL",
    "Bankhead Lake": "BANK",
    "Bardwell Lake": "BARD",
    "Barre Falls Reservoir": "BARR",
    "Barren River Lake": "BARR",
    "Bay Springs Lake": "BAYS",
    "Bear Creek Lake": "BEAR",
    "Beaver Lake": "BEAV",
    "Beech Fork Lake": "BEEC",
    "Belton Lake": "BELT",
    "Beltzville Lake": "BELT",
    "Benbrook Lake": "BENB",
    "Berlin Lake": "BERL",
    "Big Hill Lake": "BIGH",
    "Big Sandy Lake Reservoir": "BIGS",
    "Birch Hill Reservoir": "BIRC",
    "Birch Lake": "BIRC",
    "Black Butte Lake": "BLAC",
    "Blue Marsh Lake": "BLUM",
    "Blue Mountain Lake": "BLUM",
    "Blue River Lake": "BLUR",
    "Blue Springs Lake": "BLUE",
    "Bluestem Lake": "BLUE",
    "Bluestone Lake": "BLUE",
    "Bowman-Haley Lake": "BOWM",
    "Branched Oak Lake": "BROA",
    "Broken Bow Lake": "BROB",
    "Brookville Lake": "BROO",
    "Buckhorn Lake": "BUCK",
    "Buffumville Lake": "BUFF",
    "Bull Shoals Lake": "BULS",
    "Burnsville Lake": "BURN",
    "Burr Oak Reservoir": "BURR",
    "Caddo Lake": "CADD",
    "Caesar Creek Lake": "CAES",
    "Cagles Mill Lake": "CAGL",
    "Canton Lake": "CANT",
    "Canyon Lake": "CANY",
    "Carlyle Lake": "CARL",
    "Carr Creek Lake": "CARR",
    "Carters Lake": "CART",
    "Cave Run Lake": "CAVE",
    "Cecil M. Hardin Lake": "HARD",
    "Center Hill Lake": "CENT",
    "Charles Mill Lake": "CHAR",
    "Chatfield Lake": "CHAT",
    "Cheatham Lake": "CHEA",
    "Cherry Creek Lake": "CHER",
    "Claiborne Lake": "CLAI",
    "Clarence J. Brown Reservoir": "CLAR",
    "Clearwater Lake": "CLEA",
    "Clendening Lake": "CLEN",
    "Clinton Lake": "CLIN",
    "Cochiti Reservoir": "COCH",
    "Coffeeville Lake": "COFF",
    "Cold Brook Lake": "COLD",
    "Columbus Lake": "COLU",
    "Conchas Reservoir": "CONC",
    "Conemaugh River Lake": "CONE",
    "Conestoga Lake": "CONE",
    "Copan Lake": "COPA",
    "Coralville Lake": "CORA",
    "Cordell Hull Lake": "HULL",
    "Cottage Grove Lake": "COTT",
    "Cottonwood Springs Lake": "COTW",
    "Cougar Lake": "COUG",
    "Council Grove Lake": "COUN",
    "Cowanesque Lake": "COWA",
    "Crooked Creek Lake": "CROO",
    "Curwensville Lake": "CURW",
    "Dale Hollow Lake": "DALE",
    "Dardanelle Lake": "DARD",
    "DeGray Lake": "DEGR",
    "DeQueen Reservoir": "DEQU",
    "Deer Creek Lake": "DEER",
    "Delaware Lake": "DELA",
    "Demopolis Lake": "DEMO",
    "Detroit Lake": "DETR",
    "Dewey Lake": "DEWE",
    "Dexter Lake": "DEXT",
    "Dierks Reservoir": "DIER",
    "Dillon Lake": "DILL",
    "Dorena Lake": "DORE",
    "Dworshak Reservoir": "DWOR",
    "East Branch Clarion River Lake": "EBCR",
    "East Lynn Lake": "ELYN",
    "Edward MacDowell Lake": "MACD",
    "El Dorado Lake": "ELDO",
    "Elk City Lake": "ELKC",
    "Englebright Lake": "ENGL",
    "Enid Lake": "ENID",
    "Eufaula Lake": "EUFA",
    "F. E. Walter Reservoir": "WALT",
    "Fall Creek Lake": "FALC",
    "Fall River Lake": "FALL",
    "Falls Lake": "FALL",
    "Farmington Reservoir": "FARM",
    "Fern Ridge Lake": "FERN",
    "Fishtrap Lake": "FISH",
    "Fort Gibson Lake": "FOGI",
    "Fort Peck Lake": "FPEC",
    "Fort Supply Lake": "FSUP",
    "Foster Joseph Sayers Reservoir": "FOST",
    "Foster Lake": "FOST",
    "Franklin Falls Reservoir": "FRAN",
    "Gainesville Lake": "GAIN",
    "Galisteo Reservoir": "GALI",
    "George W Andrews Lake": "ANDR",
    "Georgetown Lake": "GEOR",
    "Gillham Lake": "GILL",
    "Granger Lake": "GRAN",
    "Grapevine Lake": "GRAP",
    "Grayson Lake": "GRAY",
    "Great Salt Plains Lake": "GSPL",
    "Green Peter Lake": "GRPE",
    "Green River Lake": "GREN",
    "Greers Ferry Lake": "GREF",
    "Grenada Lake": "GREN",
    "Gull Lake": "GULL",
    "H. V. Eastman Lake": "EAST",
    "Hammond Lake": "HAMM",
    "Harlan County Lake": "HARL",
    "Harry S. Truman Lake": "TRUM",
    "Hartwell Lake": "HART",
    "Hensley Lake": "HENS",
    "Heyburn Lake": "HEYB",
    "Hills Creek Lake": "HILL",
    "Hillsdale Lake": "HILL",
    "Holmes Lake": "HOLM",
    "Holt Lake": "HOLT",
    "Homme Lake": "HOMM",
    "Hopkinton Lake": "HOPK",
    "Hords Creek Lake": "HORD",
    "Howard A. Hanson Reservoir": "HANS",
    "Hugo Lake": "HUGO",
    "Hulah Lake": "HULA",
    "Isabella Lake": "ISAB",
    "J. Edward Roush Lake": "ROUS",
    "J. Percy Priest Lake": "PRIE",
    "J. Strom Thurmond Lake": "THUR",
    "Jemez Canyon Reservoir": "JEME",
    "Jennings Randolph Lake": "JENN",
    "Jim Chapman Lake": "CHAP",
    "Joe Pool Lake": "JOPO",
    "John H. Kerr Reservoir": "JOHN",
    "John Martin Reservoir": "JOHN",
    "John Redmond Reservoir": "JOHN",
    "Kanopolis Lake": "KANO",
    "Kaw Lake": "KAWK",
    "Kettle Creek Lake": "KETT",
    "Keystone Lake": "KEYS",
    "Knightville Reservoir": "KNIG",
    "Lac Qui Parle Lake": "LACP",
    "Lake Allatoona": "ALLA",
    "Lake Ashtabula": "ASHT",
    "Lake Barkley": "BARK",
    "Lake Bonneville": "BONN",
    "Lake Bryan": "BRYA",
    "Lake Celilo": "CELI",
    "Lake Clementine": "CLEM",
    "Lake Cumberland": "CUMB",
    "Lake Francis Case": "FRAN",
    "Lake Greeson": "GREE",
    "Lake Herbert G West": "HERB",
    "Lake Kaweah": "KAWE",
    "Lake Koocanusa": "KOOC",
    "Lake Mendocino": "MEND",
    "Lake O' The Pines": "OPIN",
    "Lake Oahe": "OAHE",
    "Lake Ouachita": "OUAC",
    "Lake Pend Oreille": "PEND",
    "Lake Ray Roberts": "ROBE",
    "Lake Red Rock": "REDR",
    "Lake Sacajawea": "SACA",
    "Lake Sakakawea": "SAKA",
    "Lake Seminole": "SEMI",
    "Lake Sharpe": "SHAR",
    "Lake Shelbyville": "SHEL",
    "Lake Sidney Lanier": "LANI",
    "Lake Sonoma": "SONO",
    "Lake Success": "SUCC",
    "Lake Texoma": "DENI",
    "Lake Traverse": "TRAV",
    "Lake Umatilla": "UMAT",
    "Lake Wallula": "WALL",
    "Lake Winnibigoshish": "WINN",
    "Laurel River Lake": "LAUR",
    "Lavon Lake": "LAVO",
    "Leech Lake": "LEEC",
    "Leesville Lake": "LEES",
    "Lewis and Clark Lake": "LEWI",
    "Lewisville Lake": "LEWI",
    "Littleville Lake": "LITT",
    "Long Branch Lake": "LONB",
    "Longview Lake": "LONG",
    "Lookout Point Lake": "LOOK",
    "Lost Creek Lake": "LOST",
    "Lower Granite Lake": "LOWE",
    "Loyalhanna Lake": "LOYA",
    "Lucky Peak Lake": "LUCK",
    "Mahoning Creek Lake": "MAHO",
    "Marion Lake": "MARI",
    "Mark Twain Lake": "MTWN",
    "Marsh Lake": "MARS",
    "Martins Fork Lake": "MART",
    "Martis Creek Lake": "MART",
    "Melvern Lake": "MELV",
    "Michael J. Kirwan Reservoir": "KIRW",
    "Milford Lake": "MILD",
    "Millwood Lake": "MILL",
    "Mississinewa Lake": "MISS",
    "Monroe Lake": "MONR",
    "Mosquito Creek Lake": "MOSQ",
    "Navarro Mills Lake": "NAVA",
    "New Hogan Lake": "NHOG",
    "Nimrod Lake": "NIMR",
    "Nolin River Lake": "NOLI",
    "Norfork Lake": "NORF",
    "North Springfield Reservoir": "NOSP",
    "O. C. Fisher Lake": "FISH",
    "Okatibbee Lake": "OKAT",
    "Old Hickory Lake": "OHIC",
    "Olive Creek Lake": "OLIV",
    "Oliver Lake": "OLIV",
    "Oologah Lake": "OOLO",
    "Optima Lake": "OPTI",
    "Orwell Lake": "ORWE",
    "Otter Brook Lake": "OTTE",
    "Ozark Lake": "OZAR",
    "Paint Creek Lake": "PAIN",
    "Pat Mayse Lake": "PATS",
    "Patoka Lake": "PATO",
    "Pawnee Lake": "PAWN",
    "Perry Lake": "PERR",
    "Piedmont Lake": "PIED",
    "Pine Creek Lake": "PINC",
    "Pine Flat Lake": "PINF",
    "Pine River Reservoir": "PINR",
    "Pipestem Lake": "PIPE",
    "Pleasant Hill Lake": "PLEA",
    "Pokegama Lake": "POKE",
    "Pomme de Terre Lake": "POMT",
    "Pomona Lake": "POMO",
    "Proctor Lake": "PROC",
    "Prompton Lake": "PROM",
    "R. D. Bailey Lake": "BAIL",
    "R. E. Bob Woodruff Lake": "WOOD",
    "Rathbun Lake": "RATH",
    "Raystown Lake": "RAYS",
    "Rend Lake": "REND",
    "Richard B. Russell Lake": "RUSS",
    "Robert S. Kerr Lake": "KERR",
    "Rough River Lake": "ROUG",
    "Rufus Woods Lake": "RUFU",
    "Salamonie Lake": "SALA",
    "Sam Rayburn Reservoir": "SAMR",
    "Santa Rosa Reservoir": "SANR",
    "Sardis Lake": "SARD",
    "Savage River Reservoir": "SAVA",
    "Saylorville Lake": "SAYL",
    "Senecaville Lake": "SENE",
    "Shenango River Lake": "SHEN",
    "Skiatook Lake": "SKIA",
    "Smithville Lake": "SMIT",
    "Somerville Lake": "SOME",
    "Stagecoach Lake": "STAG",
    "Standing Bear Lake": "BEAR",
    "Steinhagen Lake": "STEI",
    "Stillhouse Hollow Lake": "STIL",
    "Stillwater Lake": "STIL",
    "Stockton Lake": "STOC",
    "Stonewall Jackson Lake": "STON",
    "Summersville Lake": "SUMM",
    "Surry Mountain Lake": "SURR",
    "Sutton Lake": "SUTT",
    "Table Rock Lake": "TABR",
    "Tappan Lake": "TAPP",
    "Taylorsville Lake": "TAYL",
    "Tenkiller Ferry Lake": "TENK",
    "Tennessee-Tombigbee Waterway at Fulton": "FULT",
    "Tennessee-Tombigbee Waterway at G. V. Montgomery": "MONT",
    "Tennessee-Tombigbee Waterway at Glover Wilkins": "WILK",
    "Tioga Lake": "TIOG",
    "Tionesta Lake": "TION",
    "Toronto Lake": "TORO",
    "Townshend Reservoir": "TOWN",
    "Trinidad Reservoir": "TRIN",
    "Tully Lake": "TULL",
    "Tuttle Creek Lake": "TUTC",
    "Twin Lakes": "TWIN",
    "Two Rivers Reservoir": "TWOR",
    "Tygart Lake": "TYGA",
    "Union City Lake": "UNIO",
    "Union Village Reservoir": "UNIO",
    "Upper & Lower Red Lake": "REDL",
    "W. Kerr Scott Reservoir": "KERR",
    "Waco Lake": "WACO",
    "Wagon Train Lake": "WAGO",
    "Wallace Lake": "WALL",
    "Walter F. George Lake": "GEOR",
    "Wappapello Lake": "WAPP",
    "Warrior Lake": "WARR",
    "Waurika Lake": "WAUR",
    "West Fork Lake": "WESF",
    "West Point Lake": "WESP",
    "Whitney Lake": "WHIT",
    "Whitney Point Lake": "WHIT",
    "William Dannelly Reservoir": "DANN",
    "William H Harsha Lake": "HARS",
    "Wilson Lake": "WILS",
    "Wister Lake": "WIST",
    "Woodcock Creek Lake": "WOOD",
    "Wright Patman Lake": "WRIP",
    "Yankee Hill Lake": "YANK",
    "Youghiogheny River Lake": "YOUG",
    "Zorinsky Lake": "ZORI",
}
